config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :create, :new, :update, :edit]
  resources :cat_rental_requests, only: [:new, :create]

  post 'approve', to: 'cat_rental_requests#approve!', as: :approve
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLOR = %w(blue purple pink orange green red gray)

  validates :birth_date, :name, :description, :color, presence: true
  validates :color, inclusion: { in: COLOR, message: "Cat can't be that color" }
  validates :sex, inclusion: { in: %w(F M), message: "Sex only exists as a binary concept for cats" }

  def age
    time_ago_in_words(birth_date)
  end

  has_many :requests, dependent: :destroy,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(APPROVED PENDING DENIED), message: "Invalid status!" }
  validate :does_not_overlap_approved_request # message: "This cat is already booked!"

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def approve!
    if self.status == "PENDING"
      CatRentalRequest.transaction do
        self.status = "APPROVED"
        overlapping_requests.each do |request|
          request.status = "DENIED"
        end
      end
    end
  end

  def deny!
    self.status = "DENIED"
  end

  def pending?
    self.status == "PENDING"
  end

  def overlapping_requests
    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
         NOT( (start_date > :end_date) OR (end_date < :start_date) )
      SQL
  end

  def overlapping_approved_requests
    overlapping_requests
      .where("status = 'APPROVED'")
  end

  def does_not_overlap_approved_request
    overlapping_approved_requests.exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    render :new
  end

  def create
    @request = CatRentalRequest.new(request_params)
    if @request.save
      redirect_to cat_url(@request.cat_id)
    else
      flash.now[:errors] = @request.errors.full_messages
      render :new
    end
  end

  private
  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = selected_cat
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = selected_cat
    render :edit
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def update
    @cat = selected_cat

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private
  def selected_cat
    Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1> Make a request to rent our cats!!! </h1>

<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<form action="<%= cat_rental_requests_url %>" method="POST">

  <label>Cat:
    <select name="cat_rental_request[cat_id]" />
      <option disabled selected>--Pick a cat--</option>
      <% Cat.all.each do |cat| %>
        <option value="<%= cat.id %>"> <%= cat.name %> </option>
      <% end %>
    </select>
  </label>

  <br>

  <label>Start date:
    <input type='date' name="cat_rental_request[start_date]">
  </label>

  <br>

  <label>end date:
    <input type='date' name="cat_rental_request[end_date]">
  </label>

  <br>

  <input type="submit" value="Make Rental Request" >
</form>

app/views/cats/_form.html.erb
<% _action = cat.id ? cat_url(cat) : cats_url %>
<% _verb = cat.id ? "PATCH" : "POST" %>

<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<form action="<%= _action %>" method="POST">
  <input type="hidden" name="_method" value="<%= _verb %>">

  <label>Name:
    <input type="text" name="cat[name]" value=" <%= cat.name %> " />
  </label>

  <br>

  <label>Sex:
    <label><input type="radio" name="cat[sex]" value="F" checked = "<%= cat.sex == "F" ? "checked" : "" %> " />F</label>
    <label><input type="radio" name="cat[sex]" value="M" checked = "<%= cat.sex == "M" ? "checked" : "" %> "/>M</label>
  </label>

  <br>

  <label>Color:
    <select name="cat[color]" />
      <option disabled>--Pick a color--</option>
      <% Cat::COLOR.each do |color| %>
        <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %>> <%= color %> </option>
      <% end %>
    </select>
  </label>

  <br>

  <label>Date:
    <input type='date' name="cat[birth_date]" value= "<%= cat.birth_date %>" >
  </label>

  <br>

  <label>Description:
    <textarea name="cat[description]"> <%= cat.description %> </textarea>
  </label>

  <br>

  <input type="submit" value="<%= _verb == "PATCH" ? "Edit this cat" : "Add this cat" %>">
</form>

app/views/cats/edit.html.erb
<h1>Edit a cat!</h1>

<%= render 'form', cat: @cat %>

app/views/cats/index.html.erb
<h1>All of the BEST kitty cats in the world</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><%= cat.name %>:
    <%= link_to "show me more about this cat!", cat_url(cat) %></li>
  <% end %>
</ul>

<%= link_to "Add a new kitty cat!", new_cat_url %>

app/views/cats/new.html.erb
<h1>Add a new cat!</h1>

<%= render 'form', cat: @cat %>

app/views/cats/show.html.erb
<h1>Information about <%= @cat.name %></h1>

<table>
  <tr>
      <th><h3>All about <%= @cat.name %></h3></th>
  </tr>
  <tr>
    <td> Age </td>
    <td> <%= @cat.age %> </td>
  </tr>
  <tr>
    <td> Birthday </td>
    <td> <%= @cat.birth_date %> </td>
  </tr>
  <tr>
    <td> Color </td>
    <td> <%= @cat.color %> </td>
  </tr>
  <tr>
    <td> Sex </td>
    <td> <%= @cat.sex %> </td>
  </tr>
  <tr>
    <td> Description </td>
    <td> <%= @cat.description %> </td>
  </tr>
</table>

  <br>
  <h3>Here are all the current requests for <%= @cat.name %></h3>
  <% requests = CatRentalRequest %>
  <%  .where(cat_id: @cat.id) %>
  <%  .order(:start_date) %>

  <% if requests.empty? %>
  <p>There are no requests for the cat yet! :)</p>
  <% else %>
  <ul>
    <% requests.each do |request| %>
      <li>
        <%= request.start_date %> to <%= request.end_date %> : <%= request.status %>
        <% if request.pending? %><%= button_to "Approve meow", approve_url %><% end %>
      </li>
    <% end %>
  </ul>
  <% end %>


<br>
<%= link_to "Request this cat!", new_cat_rental_request_url %>
<br>
<%= link_to "Edit this cat!", edit_cat_url(@cat) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentCat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>